### ISSUE TITLE
version bump

### ISSUE THREAD

**Issue by lukeasrodgers** [rgrove/cssmin#5]
Would it be possible to get a version bump that includes the latest fixes (especially the one involving the incorrect stripping of whitespace in media queries) so that it's easier for other gems that depend on cssmin (e.g. Jammit) to get this fix by default?

Jammit currently depends on cssmin version 1.0.2 which has the aforementioned bug.

**Comment by rgrove** [comment]
Enjoy! http://rubygems.org/gems/cssmin/versions/1.0.3

**Comment by lukeasrodgers** [comment]
Awesome, thanks!
